// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raftPersistDate.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_raftPersistDate_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_raftPersistDate_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021011 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_raftPersistDate_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_raftPersistDate_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_raftPersistDate_2eproto;
namespace raftPersistDate {
class LogEntry;
struct LogEntryDefaultTypeInternal;
extern LogEntryDefaultTypeInternal _LogEntry_default_instance_;
class PersistRaftNode;
struct PersistRaftNodeDefaultTypeInternal;
extern PersistRaftNodeDefaultTypeInternal _PersistRaftNode_default_instance_;
}  // namespace raftPersistDate
PROTOBUF_NAMESPACE_OPEN
template<> ::raftPersistDate::LogEntry* Arena::CreateMaybeMessage<::raftPersistDate::LogEntry>(Arena*);
template<> ::raftPersistDate::PersistRaftNode* Arena::CreateMaybeMessage<::raftPersistDate::PersistRaftNode>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace raftPersistDate {

// ===================================================================

class LogEntry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raftPersistDate.LogEntry) */ {
 public:
  inline LogEntry() : LogEntry(nullptr) {}
  ~LogEntry() override;
  explicit PROTOBUF_CONSTEXPR LogEntry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LogEntry(const LogEntry& from);
  LogEntry(LogEntry&& from) noexcept
    : LogEntry() {
    *this = ::std::move(from);
  }

  inline LogEntry& operator=(const LogEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogEntry& operator=(LogEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LogEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const LogEntry* internal_default_instance() {
    return reinterpret_cast<const LogEntry*>(
               &_LogEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LogEntry& a, LogEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(LogEntry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogEntry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LogEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LogEntry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LogEntry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LogEntry& from) {
    LogEntry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogEntry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raftPersistDate.LogEntry";
  }
  protected:
  explicit LogEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommandFieldNumber = 3,
    kTermFieldNumber = 1,
    kIndexFieldNumber = 2,
  };
  // string command = 3;
  void clear_command();
  const std::string& command() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_command(ArgT0&& arg0, ArgT... args);
  std::string* mutable_command();
  PROTOBUF_NODISCARD std::string* release_command();
  void set_allocated_command(std::string* command);
  private:
  const std::string& _internal_command() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_command(const std::string& value);
  std::string* _internal_mutable_command();
  public:

  // int32 term = 1;
  void clear_term();
  int32_t term() const;
  void set_term(int32_t value);
  private:
  int32_t _internal_term() const;
  void _internal_set_term(int32_t value);
  public:

  // int32 index = 2;
  void clear_index();
  int32_t index() const;
  void set_index(int32_t value);
  private:
  int32_t _internal_index() const;
  void _internal_set_index(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:raftPersistDate.LogEntry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr command_;
    int32_t term_;
    int32_t index_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raftPersistDate_2eproto;
};
// -------------------------------------------------------------------

class PersistRaftNode final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raftPersistDate.PersistRaftNode) */ {
 public:
  inline PersistRaftNode() : PersistRaftNode(nullptr) {}
  ~PersistRaftNode() override;
  explicit PROTOBUF_CONSTEXPR PersistRaftNode(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PersistRaftNode(const PersistRaftNode& from);
  PersistRaftNode(PersistRaftNode&& from) noexcept
    : PersistRaftNode() {
    *this = ::std::move(from);
  }

  inline PersistRaftNode& operator=(const PersistRaftNode& from) {
    CopyFrom(from);
    return *this;
  }
  inline PersistRaftNode& operator=(PersistRaftNode&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PersistRaftNode& default_instance() {
    return *internal_default_instance();
  }
  static inline const PersistRaftNode* internal_default_instance() {
    return reinterpret_cast<const PersistRaftNode*>(
               &_PersistRaftNode_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PersistRaftNode& a, PersistRaftNode& b) {
    a.Swap(&b);
  }
  inline void Swap(PersistRaftNode* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PersistRaftNode* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PersistRaftNode* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PersistRaftNode>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PersistRaftNode& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PersistRaftNode& from) {
    PersistRaftNode::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PersistRaftNode* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raftPersistDate.PersistRaftNode";
  }
  protected:
  explicit PersistRaftNode(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLogsFieldNumber = 5,
    kCurrentTermFieldNumber = 1,
    kVotedForFieldNumber = 2,
    kLastSnapshotIncludeIndexFieldNumber = 3,
    kLastSnapshotIncludeTermFieldNumber = 4,
  };
  // repeated .raftPersistDate.LogEntry logs = 5;
  int logs_size() const;
  private:
  int _internal_logs_size() const;
  public:
  void clear_logs();
  ::raftPersistDate::LogEntry* mutable_logs(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raftPersistDate::LogEntry >*
      mutable_logs();
  private:
  const ::raftPersistDate::LogEntry& _internal_logs(int index) const;
  ::raftPersistDate::LogEntry* _internal_add_logs();
  public:
  const ::raftPersistDate::LogEntry& logs(int index) const;
  ::raftPersistDate::LogEntry* add_logs();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raftPersistDate::LogEntry >&
      logs() const;

  // int32 current_term = 1;
  void clear_current_term();
  int32_t current_term() const;
  void set_current_term(int32_t value);
  private:
  int32_t _internal_current_term() const;
  void _internal_set_current_term(int32_t value);
  public:

  // int32 voted_for = 2;
  void clear_voted_for();
  int32_t voted_for() const;
  void set_voted_for(int32_t value);
  private:
  int32_t _internal_voted_for() const;
  void _internal_set_voted_for(int32_t value);
  public:

  // int32 last_snapshot_include_index = 3;
  void clear_last_snapshot_include_index();
  int32_t last_snapshot_include_index() const;
  void set_last_snapshot_include_index(int32_t value);
  private:
  int32_t _internal_last_snapshot_include_index() const;
  void _internal_set_last_snapshot_include_index(int32_t value);
  public:

  // int32 last_snapshot_include_term = 4;
  void clear_last_snapshot_include_term();
  int32_t last_snapshot_include_term() const;
  void set_last_snapshot_include_term(int32_t value);
  private:
  int32_t _internal_last_snapshot_include_term() const;
  void _internal_set_last_snapshot_include_term(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:raftPersistDate.PersistRaftNode)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raftPersistDate::LogEntry > logs_;
    int32_t current_term_;
    int32_t voted_for_;
    int32_t last_snapshot_include_index_;
    int32_t last_snapshot_include_term_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raftPersistDate_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LogEntry

// int32 term = 1;
inline void LogEntry::clear_term() {
  _impl_.term_ = 0;
}
inline int32_t LogEntry::_internal_term() const {
  return _impl_.term_;
}
inline int32_t LogEntry::term() const {
  // @@protoc_insertion_point(field_get:raftPersistDate.LogEntry.term)
  return _internal_term();
}
inline void LogEntry::_internal_set_term(int32_t value) {
  
  _impl_.term_ = value;
}
inline void LogEntry::set_term(int32_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raftPersistDate.LogEntry.term)
}

// int32 index = 2;
inline void LogEntry::clear_index() {
  _impl_.index_ = 0;
}
inline int32_t LogEntry::_internal_index() const {
  return _impl_.index_;
}
inline int32_t LogEntry::index() const {
  // @@protoc_insertion_point(field_get:raftPersistDate.LogEntry.index)
  return _internal_index();
}
inline void LogEntry::_internal_set_index(int32_t value) {
  
  _impl_.index_ = value;
}
inline void LogEntry::set_index(int32_t value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:raftPersistDate.LogEntry.index)
}

// string command = 3;
inline void LogEntry::clear_command() {
  _impl_.command_.ClearToEmpty();
}
inline const std::string& LogEntry::command() const {
  // @@protoc_insertion_point(field_get:raftPersistDate.LogEntry.command)
  return _internal_command();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LogEntry::set_command(ArgT0&& arg0, ArgT... args) {
 
 _impl_.command_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:raftPersistDate.LogEntry.command)
}
inline std::string* LogEntry::mutable_command() {
  std::string* _s = _internal_mutable_command();
  // @@protoc_insertion_point(field_mutable:raftPersistDate.LogEntry.command)
  return _s;
}
inline const std::string& LogEntry::_internal_command() const {
  return _impl_.command_.Get();
}
inline void LogEntry::_internal_set_command(const std::string& value) {
  
  _impl_.command_.Set(value, GetArenaForAllocation());
}
inline std::string* LogEntry::_internal_mutable_command() {
  
  return _impl_.command_.Mutable(GetArenaForAllocation());
}
inline std::string* LogEntry::release_command() {
  // @@protoc_insertion_point(field_release:raftPersistDate.LogEntry.command)
  return _impl_.command_.Release();
}
inline void LogEntry::set_allocated_command(std::string* command) {
  if (command != nullptr) {
    
  } else {
    
  }
  _impl_.command_.SetAllocated(command, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.command_.IsDefault()) {
    _impl_.command_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:raftPersistDate.LogEntry.command)
}

// -------------------------------------------------------------------

// PersistRaftNode

// int32 current_term = 1;
inline void PersistRaftNode::clear_current_term() {
  _impl_.current_term_ = 0;
}
inline int32_t PersistRaftNode::_internal_current_term() const {
  return _impl_.current_term_;
}
inline int32_t PersistRaftNode::current_term() const {
  // @@protoc_insertion_point(field_get:raftPersistDate.PersistRaftNode.current_term)
  return _internal_current_term();
}
inline void PersistRaftNode::_internal_set_current_term(int32_t value) {
  
  _impl_.current_term_ = value;
}
inline void PersistRaftNode::set_current_term(int32_t value) {
  _internal_set_current_term(value);
  // @@protoc_insertion_point(field_set:raftPersistDate.PersistRaftNode.current_term)
}

// int32 voted_for = 2;
inline void PersistRaftNode::clear_voted_for() {
  _impl_.voted_for_ = 0;
}
inline int32_t PersistRaftNode::_internal_voted_for() const {
  return _impl_.voted_for_;
}
inline int32_t PersistRaftNode::voted_for() const {
  // @@protoc_insertion_point(field_get:raftPersistDate.PersistRaftNode.voted_for)
  return _internal_voted_for();
}
inline void PersistRaftNode::_internal_set_voted_for(int32_t value) {
  
  _impl_.voted_for_ = value;
}
inline void PersistRaftNode::set_voted_for(int32_t value) {
  _internal_set_voted_for(value);
  // @@protoc_insertion_point(field_set:raftPersistDate.PersistRaftNode.voted_for)
}

// int32 last_snapshot_include_index = 3;
inline void PersistRaftNode::clear_last_snapshot_include_index() {
  _impl_.last_snapshot_include_index_ = 0;
}
inline int32_t PersistRaftNode::_internal_last_snapshot_include_index() const {
  return _impl_.last_snapshot_include_index_;
}
inline int32_t PersistRaftNode::last_snapshot_include_index() const {
  // @@protoc_insertion_point(field_get:raftPersistDate.PersistRaftNode.last_snapshot_include_index)
  return _internal_last_snapshot_include_index();
}
inline void PersistRaftNode::_internal_set_last_snapshot_include_index(int32_t value) {
  
  _impl_.last_snapshot_include_index_ = value;
}
inline void PersistRaftNode::set_last_snapshot_include_index(int32_t value) {
  _internal_set_last_snapshot_include_index(value);
  // @@protoc_insertion_point(field_set:raftPersistDate.PersistRaftNode.last_snapshot_include_index)
}

// int32 last_snapshot_include_term = 4;
inline void PersistRaftNode::clear_last_snapshot_include_term() {
  _impl_.last_snapshot_include_term_ = 0;
}
inline int32_t PersistRaftNode::_internal_last_snapshot_include_term() const {
  return _impl_.last_snapshot_include_term_;
}
inline int32_t PersistRaftNode::last_snapshot_include_term() const {
  // @@protoc_insertion_point(field_get:raftPersistDate.PersistRaftNode.last_snapshot_include_term)
  return _internal_last_snapshot_include_term();
}
inline void PersistRaftNode::_internal_set_last_snapshot_include_term(int32_t value) {
  
  _impl_.last_snapshot_include_term_ = value;
}
inline void PersistRaftNode::set_last_snapshot_include_term(int32_t value) {
  _internal_set_last_snapshot_include_term(value);
  // @@protoc_insertion_point(field_set:raftPersistDate.PersistRaftNode.last_snapshot_include_term)
}

// repeated .raftPersistDate.LogEntry logs = 5;
inline int PersistRaftNode::_internal_logs_size() const {
  return _impl_.logs_.size();
}
inline int PersistRaftNode::logs_size() const {
  return _internal_logs_size();
}
inline void PersistRaftNode::clear_logs() {
  _impl_.logs_.Clear();
}
inline ::raftPersistDate::LogEntry* PersistRaftNode::mutable_logs(int index) {
  // @@protoc_insertion_point(field_mutable:raftPersistDate.PersistRaftNode.logs)
  return _impl_.logs_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raftPersistDate::LogEntry >*
PersistRaftNode::mutable_logs() {
  // @@protoc_insertion_point(field_mutable_list:raftPersistDate.PersistRaftNode.logs)
  return &_impl_.logs_;
}
inline const ::raftPersistDate::LogEntry& PersistRaftNode::_internal_logs(int index) const {
  return _impl_.logs_.Get(index);
}
inline const ::raftPersistDate::LogEntry& PersistRaftNode::logs(int index) const {
  // @@protoc_insertion_point(field_get:raftPersistDate.PersistRaftNode.logs)
  return _internal_logs(index);
}
inline ::raftPersistDate::LogEntry* PersistRaftNode::_internal_add_logs() {
  return _impl_.logs_.Add();
}
inline ::raftPersistDate::LogEntry* PersistRaftNode::add_logs() {
  ::raftPersistDate::LogEntry* _add = _internal_add_logs();
  // @@protoc_insertion_point(field_add:raftPersistDate.PersistRaftNode.logs)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raftPersistDate::LogEntry >&
PersistRaftNode::logs() const {
  // @@protoc_insertion_point(field_list:raftPersistDate.PersistRaftNode.logs)
  return _impl_.logs_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace raftPersistDate

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_raftPersistDate_2eproto
